[versions]
kairo = "4.2.0" # https://github.com/hudson155/kairo/releases
osiris = "0.1.0-SNAPSHOT" # https://github.com/hudson155/osiris-ai/releases

[libraries]
kairoEnvironmentVariableSupplier = { module = "kairo:kairo-environment-variable-supplier", version.ref = "kairo" }
kairoTesting = { module = "kairo:kairo-testing", version.ref = "kairo" }
osirisCore = { module = "software.airborne.osiris:osiris-core", version.ref = "osiris" }
osirisOpenAi = { module = "software.airborne.osiris:osiris-open-ai", version.ref = "osiris" }
